### ISSUE TITLE
Extend other OSS licenses as well?

### ISSUE THREAD

**Issue by jeznag** [raisely/NoHarm#14]
As per the comment [here](https://github.com/stryker-mutator/stryker/issues/1061#issuecomment-409961544), not everyone likes BSD-3 as a base license. Would it be possible to have a variant of the license based on the Apache license as well?

**Comment by chrisjensen** [comment]
I don't have any objection to this. But it is a lot of work, because it wouldn't simply be tacking this text onto each license, there'd need to be some solid understanding of each license and resolving potential conflicts (especially the more copy-left ones).

I'd be open to accepting PR's for a folder that contained versions that could be applied to other licenses, but I wouldn't be able to commit to maintaining them.
So maybe they go in a `contrib` folder ?

**Comment by jeznag** [comment]
@chrisjensen should the Apache license be moved into a contrib directory as per your comment? It is now out of sync.

**Comment by ghost** [comment]
@jeznag @chrisjensen

You all may want to check recent commits and PRs that were saved by @tommaitland. #74 dealt with ambiguity between "shall" and "must".

**Comment by ghost** [comment]
My thought on the issue. I think that extending an OSS license may be overkill, especially with the variability in both base licenses, and the scope of NoHarm. Maybe making a customizable license-builder would be an alternative. For example, you could use [mustache](https://github.com/mustache) templates on redundant components such as the definitions:
```
...
## Definitions
{{#terms}}
"{{term}}" {{#alts}}(or {{alts}}) {{/alts}}must {{definition}}.

{{/terms}}
...
```
I'll see what else I could simplify with a template. There will not be any PR's about this until I can justify using a template, *or* if the Raisely team disapproves of the idea.
