### ISSUE TITLE
Revise the pornography section

### ISSUE THREAD

**Issue by fabianmichael** [raisely/NoHarm#29]
## Overview
While the majority of the porn is definitely produced for a male audience and includes an often very problematic representation of female actors, there are also artistic forms of porn (one could say "arthouse-porn") whose are e.g. feminist or for exploring different kinds of eroticism. Those should not be considered anti-ethical or harmful.

## Proposed Resolution
I think the license should differentiate between sth. like abusive/sexist porn an porn which is art-orientated (thought this is probably just a small percentage of all porn produced). There are also examples in avant-garde art which blur the lines between art and porn. However, I’m not an expert on this topic (haha, who would admit that anyway … ;-) ) and neither am I familiar with the terminology of porn, so further input is needed if there is any interest at all for including more ﻿differentation on this topic in the license.

**Comment by chrisjensen** [comment]
Thank you Michael. On my todo list is to reach out to more diverse groups of people to contribute, and given that (as best I can tell), all discussion of this so far has been conducted by white men, we probably want some alternate perspectives.
I'm going to leave this open until we can get some broader perspectives on this.

**Comment by jeznag** [comment]
See also discussion in https://github.com/raisely/NoHarm/pull/13

**Comment by christianbundy** [comment]
> My specific recommendation is to replace the mention of pornography by "coerced labor".

Based on this, you may be interested in the [Peer Production License](http://wiki.p2pfoundation.net/Peer_Production_License).

**Comment by termhn** [comment]
I want to provide perspective from the standpoint of a trans woman, and espouse a perspective that seems to be forgotten in the conversation so far, and that is that porn for the sake of "art" is not the only porn/sex work which does good. There are people who work in the sex trade out of necessity, but still consensually. One large group of these people is transgender people, especially trans women. There's quite a good summary of study on this here: http://www.transequality.org/sites/default/files/Meaningful%20Work-Full%20Report_FINAL_3.pdf but I thought I would pick out some important pieces and add my own commentary.

> US laws today categorize those involved in the sex trade as either criminals or victims. Either 
way, sex workers are targeted for arrest and frequently channeled into social “services” that give 
them a choice between participation and jail time. Sex workers have been at the forefront of 
those criticizing this approach for simplifying complex issues into a criminal/victim dichotomy, 
without allowing for the reality that people with few opportunities—particularly those who are 
poor, migrants, and targets of pervasive social stigma—make the best of their situations, whether 
by working a low wage job, dealing drugs, or trading sex for money.  Transgender sex workers, in 
particular, reject categorization as victims or criminals—they are individuals with needs and will 
pursue the necessary avenues to progress toward the life that they want.

This is what we want to avoid--adding to the stigma that already exists around sex work, and further hindering those who are in the sex trade from being able to work efficiently, safely, etc. While I am sympathetic to the view that there are sex workers (even a significant portion) who are "economically coerced" into participating, however I think that this is also true of many other jobs (minimum wage labor jobs especially). And, I think that the best way we can support sex workers specifically is by making the situation they are in as good as possible.

> Transgender people who struggle to support themselves and their families are placed in an extremely challenging situation due to the stigma, violence, and discrimination they face, which is often compounded by racism, poverty, and other factors. Many turn to sex work to sustain themselves, and become vulnerable to harassment, assault, and arrest. The experiences that transgender people have in the sex trade are extremely diverse and multifaceted. Many regard this involvement as work—which they may prefer to other forms of work or which may be their best or only economic option. Others regard it as an informal means of making money, sometimes supplementing other income.  In some instances, trans people become involved in the sex trade because of coercion, such as due to domestic violence perpetrated by a partner or family member. Some people have participated in the sex trade for different reasons at different times in their life and had very different experiences. The stigmatizing and criminalizing of sex work deepens the marginalization that transgender people face. NTDS respondents who had participated in the sex trade had many of the same negative experiences as other transgender people, often at higher rates—particularly transgender women and trans people of color. We cannot say whether these negative experiences caused respondents to seek income through the sex trade, or resulted from the stigma and risks associated with sex work and its criminalization. Certainly, given the high rates of sex trade participation shown in NTDS, efforts to improve the lives of trans people must prioritize addressing the stigma, marginalization, violence, and criminalization that sex workers face. **All transgender people deserve a meaningful path out of poverty and access to safe and meaningful work, no matter what that work is.** 

This also applies to any other group of marginalized people, I believe.

**Comment by Haroenv** [comment]
I also agree “coerced” should be added before able to adopt this license

**Comment by iwwmidatlanticgdc** [comment]
I agree with the above posts about stigmatizing sex-workers. And to be real--- a lot of sex-workers self-publish nowadays on their own platforms.
"While I am sympathetic to the view that there are sex workers (even a significant portion) who are "economically coerced" into participating, however I think that this is also true of many other jobs (minimum wage labor jobs especially). And, I think that the best way we can support sex workers specifically is by making the situation they are in as good as possible."
--- @termhn

**Comment by iwwmidatlanticgdc** [comment]
however, the categories "Revenge porn" and "Deepfakes" should possibly be added.

**Comment by tommaitland** [comment]
It seems like there's 2 key issues we're debating under the *pornography* exclusion in the license: 1) the rights of sex workers and 2) the production, distribution and consumption of pornography in general.

I think it's important to separate these since they're separate harms – the questions are then:

1) Does pornography harm workers in the sex industry?
2) Does pornograph harm others in society?

On 1) I think we've got pretty compelling arguments from @ReaperX and @termhn that it doesn't necessarily, and that harm exists for workers in all industries and we should protect from that. I commented in #13 something similar, that the inclusion of *pornography* in the license does not mean that the license criminalises sex workers. The license has provisions around access to human rights, freedom to assemble and associate, freedom from slavery and indentured servitude that protect all workers, regardless of the industry we work in.

You could make similar arguments for workers on an oil rig, the license should protect them but it shouldn't protect their industry.

I don't think the debate has looked at 2) much yet (beyond @ReaperX's comment) – and 2) is why it was included in the license in the first place (and when we were drafting it, why we didn't think it would be controversial).

There's a really good literature review that was commissioned by the Australian government that's worth reading [here](https://aifs.gov.au/publications/effects-pornography-children-and-young-people/part-b-review-literature) – but I'll do a TLDR version below. The lit review finds that firstly:

- The overwhelming majority of pornographic content on the internet is heterosexual, doesn't include the use of condoms (something like 98%), depicts sex as instrumental and can be categorised as degrading or exploitative of women.

> In that study [an analysis of 400 videos from the top 4 sites], violent acts towards women were present in 37.2% of scenes (compared to 3% that depicted violent acts against men)... The responses by female performers to these acts were mostly neutral "as if not affected in any manner" (Klaassen & Peter, 2015, p. 728).

The positive effects of porn from the review are:

- That the influence and role of porn for the purpose of sex education is varied, and porn *can* teach young people about "biological facts, that it is okay to be interested in sex, that sex is pleasurable, and about sexual techniques and positions."

- That some genres of porn, such as amateur porn, can have positive effects on self confidence
> In another qualitative study, young women expressed how the diverse range of people in terms of ethnicity, appearance and sexuality in "amateur" SEIM [porn] had helped them to develop their own sexual self-confidence

The negative effects of porn from the review are"

- Porn can create self esteem issues for young people
> "When sexually inexperienced adolescents are confronted with the omnipresence of sex in SEIM, they may be more likely to perceive lacking sexual experience as a constraint and thus become dissatisfied with their sexual lives" (Peter & Valkenburg, 2009b, p. 188)

- Porn creates gender roles and negative attitudes towards women
> In a quantitative study across five European countries, boys (aged 14-17) were significantly more likely to hold sexist gender attitudes if they used pornography regularly (Stanley et al., 2016). Those authors commented that: "It was particularly notable that boys who watched pornography regularly were very much more likely than those who did not do so to agree with the attitudes statement on sexual violence which was worded: 'Women lead men on sexually and then complain about the attention they get'" (Stanley et al., 2016, p. 18).

- Porn creates body image issues for young people
> One study found that increased self-objectification and body surveillance was related to male adolescents' use of pornography (Vandenbosch & Eggermont, 2013a), while other studies described this effect on female youth (Häggström-Nordin et al, 2006; Martellozzo et al., 2016; Tomson et al., 2014).

- Porn can increase sexual aggression only in men who were already aggressive
> ...research found that perpetrating sexual coercion was associated with both regularly using pornography and sending or receiving sexual images or messages (Stanley et al., 2016). Boys with more sexist gender attitudes were also more likely to have perpetrated sexual coercion (Stanley et al., 2016).

There's plenty of other effects/consequences discussed that are either neutral, slightly negative or slightly positive – but these stood out as key points with conclusive research.

For me that leads to something of a conclusion that: *there are some benefits to pornography, but on balance those benefits do not outweigh the harms*.

Personally, I'd be open to us finding ways to make our definition of pornography more nuanced to address @ReaperX and @termhn's points – but I don't know how yet. To me (based on the research above) removing pornography entirely would be irresponsible.

**Comment by termhn** [comment]
While I think that some of the above research is compelling, I think it's important to take into account that there's nothing about it that says *pornography itself* is harmful, but rather that pornography as it is commonly created today is harmful. There's something of a self-fulfilling prophecy about this, as the root cause is toxic masculinity in society, but pornography depicting toxic masculinity can help feed into more people adopting such attitudes. I'm not sure what is the best way to try to make this distinction in a license, however.

**Comment by cryptoquick** [comment]
Not simply that, but banning pornography wholesale with a cookie-cutter license actually hurts people's livelihoods, people who may not have any other choice in what they can do to support themselves. Think, trans people in rural America, who might difficulty getting jobs to provide themselves with financial security any other way, for several reasons, some of which can be quite personal to that individual. In this scenario, the only thing coercing this person to provide photos of themselves for their own personal profit is capitalism; the fact that they have bills to pay, and would otherwise have to turn to other means to support themselves.

We can have these high-minded conversations about the societal implications of pornography all we want, but sex workers will be hurt by that action, just so everyone working on this "Do No Harm" license knows. American laws already harm sex workers enough. Perpetuating this harmful policy throughout organizations simply looking to adopt good ones as a strong foundation for socially-conscious causes, should also want to avoid harming sex workers.

**Comment by termhn** [comment]
> Not simply that, but banning pornography wholesale with a cookie-cutter license actually hurts people's livelihoods, people who may not have any other choice in what they can do to support themselves.

and 

> We can have these high-minded conversations about the societal implications of pornography all we want, but sex workers will be hurt by that action, just so everyone working on this "Do No Harm" license knows. American laws already harm sex workers enough. Perpetuating this harmful policy throughout organizations simply looking to adopt good ones as a strong foundation for socially-conscious causes, should also want to avoid harming sex workers.

Are what I was trying to get at, but couldn't find a way to say eloquently ;)

**Comment by chrisjensen** [comment]
There are some good points raised in this discussion, and it’s clear that as currently worded, the pornography restriction would have harmful unintended consequences for people already marginalised.

It’s also become clear that keeping pornography in would be a major barrier to adoption.

I’ll create a PR to remove it.

Thanks to everyone who has contributed thoughtfully and respectfully to this discussion.
