### ISSUE TITLE
Add super trawlers

### ISSUE THREAD

**Issue by chrisjensen** [raisely/NoHarm#52]
## Overview
Super trawling and other destructive/unsustainable forms of fishing should be added to the exclusion list

## Proposed Resolution
Find a good definition of unsustainable fishing and add it to the exclusions

**Comment by ghost** [comment]
*(edited for clarity)*
From a biological perspective, the root cause of the unsustainability issue is that too many fish (I'm also including sharks, octopi [a.k.a. octopuses]/squid for calamari, shrimp, lobsters, etc.) that are ready to reproduce, or the fishes' eggs (e.g. caviar) are being (killed to be) eaten. Thus, there are not very many fish that can reproduce to sustain a species. A positive-feedback loop begins to occur that can eliminate a species at worst. The only way to fix the issue is to prevent the fishing industry from taking too many reproductive fish. However, I don't see how a software license has an obligation to enforce a requirement such as over-fishing.

**Comment by ghost** [comment]
This issue is starting to get a bit stale and super-trawling seems to be out of scope for me because "I don't see how a software license has an obligation to enforce a requirement such as over-fishing." Software and super-trawlers don't seem to mix at all.

**Comment by tommaitland** [comment]
Super trawlers `...derive a majority of income from actions that discourage or frustrate a sustainable environment`. I think they're already excluded.
